### ISSUE TITLE
ValueError: Missing (cmds/includes): Python.h

### ISSUE THREAD

**Issue by heartpandora** [autotest/virt-test#2055]
Python 2.7.6
Linux xx-G41MT-S2PT 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

when I run “./run -t qemu --bootstrap”，I got the traceback as follows：

Internal error, traceback follows...
Traceback (most recent call last):
  File "./run", line 881, in _process_options
    self.option_parser.default_guest_os))
  File "/vmp/virt-test/virttest/bootstrap.py", line 762, in bootstrap
    verify_mandatory_programs(test_name)
  File "/vmp/virt-test/virttest/bootstrap.py", line 140, in verify_mandatory_programs
    raise ValueError('Missing (cmds/includes): %s' % " ".join(failures))
ValueError: Missing (cmds/includes): Python.h

who will tell me what i should do？

**Comment by heartpandora** [comment]
I solved that with “apt-get install python-all-dev”
ref：http://virt-test.readthedocs.org/en/latest/basic/InstallPrerequesitePackagesDebian.html
